### ISSUE TITLE
CPU Support?

### ISSUE THREAD

**Issue by LeoPapais** [fuenwang/LED2-Net#8]
Hello everyone,

First of all, thanks for sharing your work, your results are great. I'm trying to replicate them, but I'm facing some issues. First of all, my computer doesn't have a GPU so I tried changing the value of exp_args.device from 'cuda:0' to 'cpu', but I got the following error:
`RuntimeError: Attempting to deserialize object on a CUDA device but torch.cuda.is_available() is False. If you are running on a CPU-only machine, please use torch.load with map_location=torch.device('cpu') to map your storages to the CPU.
`
So I added this command, changing this line `params = torch.load(args.ckpt)` to it `params = torch.load(args.ckpt, map_location=torch.device(device))` and I think it should work, but I'm getting the following error (probably unrelated to the device issue):

```
Traceback (most recent call last):
  File "run_inference.py", line 58, in <module>
    pred_fp_down_man, pred_fp_down_man_pts = LED2Net.DuLaPost.fit_layout(pred_fp_down)
  File "/home/leo/sbdinc/LED2-Net/LED2Net/DuLaPost/layout.py", line 86, in fit_layout
    data_cnt.sort(key=lambda x: cv2.contourArea(x), reverse=True)
AttributeError: 'tuple' object has no attribute 'sort'
```

My Python version is 3.8.10 and my environment is:

> absl-py==1.0.0
> attrdict==2.0.1
> cachetools==5.0.0
> certifi==2021.10.8
> charset-normalizer==2.0.11
> cycler==0.11.0
> fonttools==4.29.1
> fvcore==0.1.5.post20220119
> google-auth==2.6.0
> google-auth-oauthlib==0.4.6
> grpcio==1.43.0
> idna==3.3
> imageio==2.14.1
> importlib-metadata==4.10.1
> iopath==0.1.9
> kiwisolver==1.3.2
> Markdown==3.3.6
> matplotlib==3.5.1
> networkx==2.6.3
> numpy==1.22.1
> oauthlib==3.2.0
> opencv-python==4.5.5.62
> packaging==21.3
> Pillow==9.0.0
> portalocker==2.3.2
> protobuf==3.19.4
> pyasn1==0.4.8
> pyasn1-modules==0.2.8
> pylsd-nova==1.2.0
> pyparsing==3.0.7
> python-dateutil==2.8.2
> pytorch3d==0.3.0
> PyWavelets==1.2.0
> PyYAML==6.0
> requests==2.27.1
> requests-oauthlib==1.3.1
> rsa==4.8
> scikit-image==0.19.1
> scipy==1.7.3
> six==1.16.0
> tabulate==0.8.9
> tensorboard==2.8.0
> tensorboard-data-server==0.6.1
> tensorboard-plugin-wit==1.8.1
> termcolor==1.1.0
> tifffile==2021.11.2
> torch==1.10.2
> torchaudio==0.10.2
> torchvision==0.11.3
> tqdm==4.62.3
> typing-extensions==4.0.1
> urllib3==1.26.8
> Werkzeug==2.0.2
> yacs==0.1.8
> zipp==3.7.0

Any help is appreciated :)

**Comment by LeoPapais** [comment]
Hello,

I'm posting it here so if anyone else has the same issue, it's documented here: I found out that this error was caused by a newer version of the opencv-python package. Pinning its version to opencv-python==4.2.0.34 made it work properly.

Bye
